# Generated by Django 4.2.10 on 2026-01-15 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_document_document_type_clause'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='detected_type_confidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('NDA_MUTUAL', 'NDA (Mutual)'), ('NDA_ONEWAY', 'NDA (One-way)'), ('SERVICE_AGREEMENT', 'Service Agreement'), ('PRIVACY_POLICY', 'Privacy Policy'), ('TERMS_CONDITIONS', 'Terms & Conditions'), ('EMPLOYMENT_AGREEMENT', 'Employment Agreement'), ('OTHER', 'Other/Unknown')], default='OTHER', max_length=30),
        ),
    ]
