# Generated by Django 4.2.10 on 2026-01-16 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_document_detected_type_confidence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='input_method',
            field=models.CharField(choices=[('FILE', 'File Upload'), ('TEXT', 'Pasted Text')], default='FILE', max_length=10),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
