# Generated by Django 4.2.10 on 2026-02-15 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_add_report_caching_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='summary_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='summary_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
